### GET users url
POST http://localhost:3000/users
Content-Type: application/json

{
  "user": {
    "username": "Jsin-Da-Rugged",
    "email": "cater-to-the-best@gmail.com",
    "password": "6798"
  }
}

