### GET users url
POST http://localhost:3000/users
Content-Type: application/json

{
  "user": {
    "username": "Tata-La-Licious",
    "email": "booty-goddess69@yahoo.com",
    "password": "2298"
  }
}

