### [POST REQUEST] create user
POST http://localhost:3000/users
Content-Type: application/json

{
  "user": {
    "username": "Tata-La-Licious",
    "email": "booty-goddess69@yahoo.com",
    "password": "2298"
  }
}
############################################################

### [POST REQUEST] log-in user
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "user": {
    "email": "booty-goddess69@yahoo.com",
    "password": "2298"
  }
}
############################################################

### [GET REQUEST] get the current user by web token
GET http://localhost:3000/user
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJUYXRhLUxhLUxpY2lvdXMiLCJpYXQiOjE2MzA4MDYyNTR9.wGakx44Zx5FisWl6fyn4JBmzLd9yYW2Ay1pAyQv1zKw
############################################################

### [PUT REQUEST]: PUT overwrites the entire entity if it
### already exists, and creates a new resource if it doesn’t exist
PUT http://localhost:3000/user
Content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJUYXRhLUxhLUxpY2lvdXMiLCJpYXQiOjE2MzA4MDYyNTR9.wGakx44Zx5FisWl6fyn4JBmzLd9yYW2Ay1pAyQv1zKw

{
  "user": {
    "bio": "This is my biography..."
  }
}

############################################################














